//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHWEBAPPMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_USERS
    {
        public int U_ID { get; set; }
        public string LOGID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PHNO { get; set; }
        public string QUALIFICATION { get; set; }
        public string SKILLS { get; set; }
        public string EXPERIENCE { get; set; }
    }
}
