//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHWEBAPPMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_COMPONY
    {
        public int C_ID { get; set; }
        public int LOGID { get; set; }
        public string C_NAME { get; set; }
        public string C_TYPE { get; set; }
        public string C_ADDRESS { get; set; }
        public Nullable<int> C_PHNO { get; set; }
        public string C_EMAIL { get; set; }
    }
}
