//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHWEBAPPMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_APPLICATION
    {
        public int Apply_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Comp_ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ResumeUpld { get; set; }
    }
}
